[package]
name = "_policy"
version = "0.0.0"
edition = "2024"

[lib]
name = "_policy"
path = "lib.rs"

[dependencies]
_core = { path = "../core", default-features = false, features = [] }
serde = { version = "^1.0", default-features = false, features = ["derive", "std"] }
thiserror = { version = "^2.0", default-features = false, features = [] }
