[package]
name = "_tracing"
version = "0.0.0"
edition = "2024"

[lib]
name = "_tracing"
path = "lib.rs"

[dependencies]
tracing = { version = "0.1.41", default-features = false, features = [] }
tracing-subscriber = { version = "0.3.20", default-features = false, features = [] }
